### ISSUE TITLE
Implement Sudoku Solver 

### ISSUE THREAD

**Issue by FazeelUsmani** [FazeelUsmani/Coding-Ninjas---Data-Structures-and-Algorithms-in-Python#21]
Given a 9*9 sudoku board, in which some entries are filled and others are 0 (0 indicates that the cell is empty), you need to find out whether the Sudoku puzzle can be solved or not i.e. return true or false.
Input Format :

9 Lines where ith line contains ith row elements separated by space

Output Format :

 true or false

Sample Input :

9 0 0 0 2 0 7 5 0 
6 0 0 0 5 0 0 4 0 
0 2 0 4 0 0 0 1 0 
2 0 8 0 0 0 0 0 0 
0 7 0 5 0 9 0 6 0 
0 0 0 0 0 0 4 0 1 
0 1 0 0 0 5 0 8 0 
0 9 0 0 7 0 0 0 4 
0 8 2 0 4 0 0 0 6

Sample Output :

true

**Comment by leli-1** [comment]
Can you assign it to me ?

**Comment by leli-1** [comment]
i will solve it with python

**Comment by FazeelUsmani** [comment]
Sure, @leli-1. Add your notebook in [Backtracking ](https://github.com/FazeelUsmani/Coding-Ninjas---Data-Structures-and-Algorithms-in-Python/tree/master/27%20Backtracking) folder
